server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///springboot_user
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.8.188:2181
  protocol:
    port: -1
  consumer:
    check: false
